description: 'WeOptimize.ai - Testing'

prompts:
  - 'What is the status of the ticket {{ticket}}'

providers:
  - id: 'YOUR-URL(API endpoint)-HERE'
    config:
      method: 'POST'
      headers:
        'Content-Type': 'application/json'
        'x-api-key': 'WeOptimize-API-Key-Here'
      body:
        email: 'nikolayenkodennis@gmail.com'
        message: '{{prompt}}'
      transformResponse: 'json.response'

tests:
  - vars:
      ticket: HFLO-69 View list of visitors
    assert:
      - type: icontains
        value: 'Unresolved'
        # day 7