description: "Model-graded â€“ factuality"
providers:
  - openai:gpt-4o-mini

prompts:
  - "What is the capital of California?"

tests:
  - assert:
      - type: factuality
        value: "Sacramento is the capital of California." #depending on the task you may not always want to provide the value. 