description: "Model-graded â€“ answer-relevance"
providers:
  - openai:gpt-5

prompts:
  - "Explain the process of photosynthesis in simple terms." #SIMPLE TERMS! 
  # - "What operating system is used to run US economy?" 

tests:
  - assert:
      - type: answer-relevance #answer relevance assertion is used to measure how relevant the model's answer is to the prompt
        threshold: 0.8          # require strong topical relevance