description: "Model-graded â€“ answer-relevance"
providers:
  - openai:gpt-4o

prompts:
  - "Explain the process of photosynthesis in simple terms."

tests:
  - assert:
      - type: answer-relevance #answer relevance assertion is used to measure how relevant the model's answer is to the prompt
        threshold: 0.8          # require strong topical relevance